#ifndef MYCCPILER_COMBINATION_KIND_H
#define MYCCPILER_COMBINATION_KIND_H
enum class CombinationKind {
  kUnknown,
  kVoid,
  kChar,
  kSignedChar,
  kUnsignedChar,
  kShort,
  kSignedShort,
  kShortInt,
  kSignedShortInt,
  kUnsignedShort,
  kUnsignedShortInt,
  kInt,
  kSigned,
  kSignedInt,
  kUnsigned,
  kUnsignedInt,
  kLong,
  kSignedLong,
  kLongInt,
  kSignedLongInt,
  kUnsignedLong,
  kUnsignedLongInt,
  kLongLong,
  kSignedLongLong,
  kLongLongInt,
  kSignedLongLongInt,
  kUnsignedLongLong,
  kUnsignedLongLongInt,
  kFloat,
  kDouble,
  kLongDouble,
  kStruct,
  kUnion,
  kEnum,
  kTypeName,
};
#endif //MYCCPILER_COMBINATION_KIND_H
